export interface Circuit {
  id: string;
  name: string;
  fullName: string;
  country: string;
  countryCode: string;
  city: string;
  length: number;
  turns: number;
  lapRecord: string;
  lapRecordHolder: string;
  coordinates: { lat: number; lng: number };
  raceDate: string;
  /** Race start time in UTC, e.g. "13:00:00Z" (from Jolpica schedule) */
  raceTime: string;
  /** Qualifying start time in UTC */
  qualifyingTime?: string;
  /** Sprint race date (Saturday), only present for sprint weekends */
  sprintDate?: string;
  /** Sprint race start time in UTC (sprint weekends only) */
  sprintTime?: string;
  round: number;
  isSprint: boolean;
  slug: string;
  trackImage: string;
  /** Whether this race has been cancelled for the season */
  cancelled?: boolean;
}

export const CIRCUITS: Record<string, Circuit> = {
  albert_park: {
    id: "albert_park",
    name: "Albert Park",
    fullName: "Australian Grand Prix",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    length: 5.278,
    turns: 14,
    lapRecord: "1:19.813",
    lapRecordHolder: "Charles Leclerc",
    coordinates: { lat: -37.8497, lng: 144.968 },
    raceDate: "2026-03-08",
    raceTime: "04:00:00Z",
    qualifyingTime: "05:00:00Z",
    round: 1,
    isSprint: false,
    slug: "australian-gp",
    trackImage: "/circuits/albert_park.webp",
  },
  shanghai: {
    id: "shanghai",
    name: "Shanghai International Circuit",
    fullName: "Chinese Grand Prix",
    country: "China",
    countryCode: "CN",
    city: "Shanghai",
    length: 5.451,
    turns: 16,
    lapRecord: "1:32.238",
    lapRecordHolder: "Michael Schumacher",
    coordinates: { lat: 31.3389, lng: 121.2198 },
    raceDate: "2026-03-15",
    raceTime: "07:00:00Z",
    qualifyingTime: "07:00:00Z",
    sprintDate: "2026-03-14",
    sprintTime: "03:00:00Z",
    round: 2,
    isSprint: true,
    slug: "chinese-gp",
    trackImage: "/circuits/shanghai.webp",
  },
  suzuka: {
    id: "suzuka",
    name: "Suzuka International Racing Course",
    fullName: "Japanese Grand Prix",
    country: "Japan",
    countryCode: "JP",
    city: "Suzuka",
    length: 5.807,
    turns: 18,
    lapRecord: "1:30.983",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 34.8431, lng: 136.5407 },
    raceDate: "2026-03-29",
    raceTime: "05:00:00Z",
    qualifyingTime: "06:00:00Z",
    round: 3,
    isSprint: false,
    slug: "japanese-gp",
    trackImage: "/circuits/suzuka.webp",
  },
  bahrain: {
    id: "bahrain",
    name: "Bahrain International Circuit",
    fullName: "Bahrain Grand Prix",
    country: "Bahrain",
    countryCode: "BH",
    city: "Sakhir",
    length: 5.412,
    turns: 15,
    lapRecord: "1:31.447",
    lapRecordHolder: "Pedro de la Rosa",
    coordinates: { lat: 26.0325, lng: 50.5106 },
    raceDate: "2026-04-12",
    raceTime: "14:00:00Z",
    round: 4,
    isSprint: false,
    slug: "bahrain-gp",
    trackImage: "/circuits/bahrain.webp",
    cancelled: true,
  },
  jeddah: {
    id: "jeddah",
    name: "Jeddah Corniche Circuit",
    fullName: "Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Jeddah",
    length: 6.174,
    turns: 27,
    lapRecord: "1:30.734",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 21.6319, lng: 39.1044 },
    raceDate: "2026-04-19",
    raceTime: "14:00:00Z",
    round: 5,
    isSprint: false,
    slug: "saudi-arabian-gp",
    trackImage: "/circuits/jeddah.webp",
    cancelled: true,
  },
  miami: {
    id: "miami",
    name: "Miami International Autodrome",
    fullName: "Miami Grand Prix",
    country: "United States",
    countryCode: "US",
    city: "Miami",
    length: 5.412,
    turns: 19,
    lapRecord: "1:29.708",
    lapRecordHolder: "Max Verstappen",
    coordinates: { lat: 25.9581, lng: -80.2389 },
    raceDate: "2026-05-03",
    raceTime: "20:00:00Z",
    qualifyingTime: "20:00:00Z",
    sprintDate: "2026-05-02",
    sprintTime: "16:00:00Z",
    round: 6,
    isSprint: true,
    slug: "miami-gp",
    trackImage: "/circuits/miami.webp",
  },
  montreal: {
    id: "montreal",
    name: "Circuit Gilles Villeneuve",
    fullName: "Canadian Grand Prix",
    country: "Canada",
    countryCode: "CA",
    city: "Montreal",
    length: 4.361,
    turns: 14,
    lapRecord: "1:13.078",
    lapRecordHolder: "Valtteri Bottas",
    coordinates: { lat: 45.5017, lng: -73.5228 },
    raceDate: "2026-05-24",
    raceTime: "20:00:00Z",
    qualifyingTime: "20:00:00Z",
    sprintDate: "2026-05-23",
    sprintTime: "16:00:00Z",
    round: 7,
    isSprint: true,
    slug: "canadian-gp",
    trackImage: "/circuits/montreal.webp",
  },
  monaco: {
    id: "monaco",
    name: "Circuit de Monaco",
    fullName: "Monaco Grand Prix",
    country: "Monaco",
    countryCode: "MC",
    city: "Monte Carlo",
    length: 3.337,
    turns: 19,
    lapRecord: "1:12.909",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 43.7347, lng: 7.4206 },
    raceDate: "2026-06-07",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 8,
    isSprint: false,
    slug: "monaco-gp",
    trackImage: "/circuits/monaco.webp",
  },
  barcelona: {
    id: "barcelona",
    name: "Circuit de Barcelona-Catalunya",
    fullName: "Barcelona Grand Prix",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    length: 4.657,
    turns: 16,
    lapRecord: "1:16.330",
    lapRecordHolder: "Max Verstappen",
    coordinates: { lat: 41.57, lng: 2.2611 },
    raceDate: "2026-06-14",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 9,
    isSprint: false,
    slug: "spanish-gp",
    trackImage: "/circuits/barcelona.webp",
  },
  spielberg: {
    id: "spielberg",
    name: "Red Bull Ring",
    fullName: "Austrian Grand Prix",
    country: "Austria",
    countryCode: "AT",
    city: "Spielberg",
    length: 4.318,
    turns: 10,
    lapRecord: "1:05.619",
    lapRecordHolder: "Carlos Sainz",
    coordinates: { lat: 47.2197, lng: 14.7647 },
    raceDate: "2026-06-28",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 10,
    isSprint: false,
    slug: "austrian-gp",
    trackImage: "/circuits/spielberg.webp",
  },
  silverstone: {
    id: "silverstone",
    name: "Silverstone Circuit",
    fullName: "British Grand Prix",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Silverstone",
    length: 5.891,
    turns: 18,
    lapRecord: "1:27.097",
    lapRecordHolder: "Max Verstappen",
    coordinates: { lat: 52.0786, lng: -1.0169 },
    raceDate: "2026-07-05",
    raceTime: "14:00:00Z",
    qualifyingTime: "15:00:00Z",
    sprintDate: "2026-07-04",
    sprintTime: "11:00:00Z",
    round: 11,
    isSprint: true,
    slug: "british-gp",
    trackImage: "/circuits/silverstone.webp",
  },
  spa: {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    fullName: "Belgian Grand Prix",
    country: "Belgium",
    countryCode: "BE",
    city: "Stavelot",
    length: 7.004,
    turns: 20,
    lapRecord: "1:46.286",
    lapRecordHolder: "Valtteri Bottas",
    coordinates: { lat: 50.4372, lng: 5.9714 },
    raceDate: "2026-07-19",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 12,
    isSprint: false,
    slug: "belgian-gp",
    trackImage: "/circuits/spa.webp",
  },
  budapest: {
    id: "budapest",
    name: "Hungaroring",
    fullName: "Hungarian Grand Prix",
    country: "Hungary",
    countryCode: "HU",
    city: "Budapest",
    length: 4.381,
    turns: 14,
    lapRecord: "1:16.627",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 47.5789, lng: 19.2486 },
    raceDate: "2026-07-26",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 13,
    isSprint: false,
    slug: "hungarian-gp",
    trackImage: "/circuits/budapest.webp",
  },
  zandvoort: {
    id: "zandvoort",
    name: "Circuit Zandvoort",
    fullName: "Dutch Grand Prix",
    country: "Netherlands",
    countryCode: "NL",
    city: "Zandvoort",
    length: 4.259,
    turns: 14,
    lapRecord: "1:11.097",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 52.3888, lng: 4.5409 },
    raceDate: "2026-08-23",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    sprintDate: "2026-08-22",
    sprintTime: "10:00:00Z",
    round: 14,
    isSprint: true,
    slug: "dutch-gp",
    trackImage: "/circuits/zandvoort.webp",
  },
  monza: {
    id: "monza",
    name: "Autodromo Nazionale Monza",
    fullName: "Italian Grand Prix",
    country: "Italy",
    countryCode: "IT",
    city: "Monza",
    length: 5.793,
    turns: 11,
    lapRecord: "1:21.046",
    lapRecordHolder: "Rubens Barrichello",
    coordinates: { lat: 45.6156, lng: 9.2811 },
    raceDate: "2026-09-06",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 15,
    isSprint: false,
    slug: "italian-gp",
    trackImage: "/circuits/monza.webp",
  },
  madrid: {
    id: "madrid",
    name: "Madrid Street Circuit",
    fullName: "Spanish Grand Prix",
    country: "Spain",
    countryCode: "ES",
    city: "Madrid",
    length: 5.47,
    turns: 20,
    lapRecord: "—",
    lapRecordHolder: "—",
    coordinates: { lat: 40.4168, lng: -3.7038 },
    raceDate: "2026-09-13",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 16,
    isSprint: false,
    slug: "madrid-gp",
    trackImage: "/circuits/madrid.webp",
  },
  baku: {
    id: "baku",
    name: "Baku City Circuit",
    fullName: "Azerbaijan Grand Prix",
    country: "Azerbaijan",
    countryCode: "AZ",
    city: "Baku",
    length: 6.003,
    turns: 20,
    lapRecord: "1:43.009",
    lapRecordHolder: "Charles Leclerc",
    coordinates: { lat: 40.3725, lng: 49.8533 },
    raceDate: "2026-09-26",
    raceTime: "11:00:00Z",
    qualifyingTime: "12:00:00Z",
    round: 17,
    isSprint: false,
    slug: "azerbaijan-gp",
    trackImage: "/circuits/baku.webp",
  },
  singapore: {
    id: "singapore",
    name: "Marina Bay Street Circuit",
    fullName: "Singapore Grand Prix",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    length: 4.94,
    turns: 19,
    lapRecord: "1:35.867",
    lapRecordHolder: "Lewis Hamilton",
    coordinates: { lat: 1.2914, lng: 103.8636 },
    raceDate: "2026-10-11",
    raceTime: "12:00:00Z",
    qualifyingTime: "13:00:00Z",
    sprintDate: "2026-10-10",
    sprintTime: "09:00:00Z",
    round: 18,
    isSprint: true,
    slug: "singapore-gp",
    trackImage: "/circuits/singapore.webp",
  },
  austin: {
    id: "austin",
    name: "Circuit of the Americas",
    fullName: "United States Grand Prix",
    country: "United States",
    countryCode: "US",
    city: "Austin",
    length: 5.513,
    turns: 20,
    lapRecord: "1:36.169",
    lapRecordHolder: "Charles Leclerc",
    coordinates: { lat: 30.1328, lng: -97.6411 },
    raceDate: "2026-10-25",
    raceTime: "20:00:00Z",
    qualifyingTime: "21:00:00Z",
    round: 19,
    isSprint: false,
    slug: "us-gp",
    trackImage: "/circuits/austin.webp",
  },
  mexico_city: {
    id: "mexico_city",
    name: "Autodromo Hermanos Rodriguez",
    fullName: "Mexico City Grand Prix",
    country: "Mexico",
    countryCode: "MX",
    city: "Mexico City",
    length: 4.304,
    turns: 17,
    lapRecord: "1:17.774",
    lapRecordHolder: "Valtteri Bottas",
    coordinates: { lat: 19.4042, lng: -99.0907 },
    raceDate: "2026-11-01",
    raceTime: "20:00:00Z",
    qualifyingTime: "21:00:00Z",
    round: 20,
    isSprint: false,
    slug: "mexico-city-gp",
    trackImage: "/circuits/mexico_city.webp",
  },
  interlagos: {
    id: "interlagos",
    name: "Autodromo Jose Carlos Pace",
    fullName: "Sao Paulo Grand Prix",
    country: "Brazil",
    countryCode: "BR",
    city: "Sao Paulo",
    length: 4.309,
    turns: 15,
    lapRecord: "1:10.540",
    lapRecordHolder: "Valtteri Bottas",
    coordinates: { lat: -23.7036, lng: -46.6997 },
    raceDate: "2026-11-08",
    raceTime: "17:00:00Z",
    qualifyingTime: "18:00:00Z",
    round: 21,
    isSprint: false,
    slug: "sao-paulo-gp",
    trackImage: "/circuits/interlagos.webp",
  },
  las_vegas: {
    id: "las_vegas",
    name: "Las Vegas Strip Circuit",
    fullName: "Las Vegas Grand Prix",
    country: "United States",
    countryCode: "US",
    city: "Las Vegas",
    length: 6.201,
    turns: 17,
    lapRecord: "1:35.490",
    lapRecordHolder: "Oscar Piastri",
    coordinates: { lat: 36.1147, lng: -115.1728 },
    raceDate: "2026-11-22",
    raceTime: "04:00:00Z",
    qualifyingTime: "04:00:00Z",
    round: 22,
    isSprint: false,
    slug: "las-vegas-gp",
    trackImage: "/circuits/las_vegas.webp",
  },
  lusail: {
    id: "lusail",
    name: "Lusail International Circuit",
    fullName: "Qatar Grand Prix",
    country: "Qatar",
    countryCode: "QA",
    city: "Lusail",
    length: 5.419,
    turns: 16,
    lapRecord: "1:24.319",
    lapRecordHolder: "Max Verstappen",
    coordinates: { lat: 25.49, lng: 51.4542 },
    raceDate: "2026-11-29",
    raceTime: "16:00:00Z",
    qualifyingTime: "18:00:00Z",
    round: 23,
    isSprint: false,
    slug: "qatar-gp",
    trackImage: "/circuits/lusail.webp",
  },
  yas_marina: {
    id: "yas_marina",
    name: "Yas Marina Circuit",
    fullName: "Abu Dhabi Grand Prix",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Abu Dhabi",
    length: 5.281,
    turns: 16,
    lapRecord: "1:26.103",
    lapRecordHolder: "Max Verstappen",
    coordinates: { lat: 24.4672, lng: 54.6031 },
    raceDate: "2026-12-06",
    raceTime: "13:00:00Z",
    qualifyingTime: "14:00:00Z",
    round: 24,
    isSprint: false,
    slug: "abu-dhabi-gp",
    trackImage: "/circuits/yas_marina.webp",
  },
} as const;

export const CIRCUIT_LIST: Circuit[] = Object.values(CIRCUITS).sort(
  (a, b) => a.round - b.round
);

export function getCircuitBySlug(slug: string): Circuit | undefined {
  return CIRCUIT_LIST.find((circuit) => circuit.slug === slug);
}

export function getNextRace(currentDate: Date = new Date()): Circuit | undefined {
  const dateStr = currentDate.toISOString().split("T")[0];
  return CIRCUIT_LIST.find((circuit) => !circuit.cancelled && circuit.raceDate >= dateStr);
}

export interface NextEvent {
  circuit: Circuit;
  eventType: "sprint" | "race";
  eventDate: string;
  /** UTC time component for the event, e.g. "13:00:00Z" */
  eventTime: string;
}

/** Fallback UTC start time used only if a circuit somehow lacks one. */
const DEFAULT_EVENT_TIME = "14:00:00Z";

/**
 * Returns the next upcoming event (sprint or race), whichever comes first.
 * On sprint weekends, this will return the sprint on Saturday before the race on Sunday.
 */
export function getNextEvent(currentDate: Date = new Date()): NextEvent | undefined {
  const dateStr = currentDate.toISOString().split("T")[0];
  for (const circuit of CIRCUIT_LIST) {
    if (circuit.cancelled) continue;
    // Check sprint first — it happens before the race on sprint weekends
    if (circuit.isSprint && circuit.sprintDate && circuit.sprintDate >= dateStr) {
      return {
        circuit,
        eventType: "sprint",
        eventDate: circuit.sprintDate,
        eventTime: circuit.sprintTime ?? DEFAULT_EVENT_TIME,
      };
    }
    if (circuit.raceDate >= dateStr) {
      return {
        circuit,
        eventType: "race",
        eventDate: circuit.raceDate,
        eventTime: circuit.raceTime ?? DEFAULT_EVENT_TIME,
      };
    }
  }
  return undefined;
}
