export interface Driver {
  id: string;
  firstName: string;
  lastName: string;
  abbreviation: string;
  number: number;
  teamId: string;
  nationality: string;
  countryCode: string;
  dateOfBirth: string;
  image: string;
  slug: string;
}

export const DRIVERS: Record<string, Driver> = {
  verstappen: {
    id: "verstappen",
    firstName: "Max",
    lastName: "Verstappen",
    abbreviation: "VER",
    number: 1,
    teamId: "red_bull",
    nationality: "Dutch",
    countryCode: "NL",
    dateOfBirth: "1997-09-30",
    image: "/drivers/verstappen.png",
    slug: "max-verstappen",
  },
  norris: {
    id: "norris",
    firstName: "Lando",
    lastName: "Norris",
    abbreviation: "NOR",
    number: 4,
    teamId: "mclaren",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1999-11-13",
    image: "/drivers/norris.png",
    slug: "lando-norris",
  },
  leclerc: {
    id: "leclerc",
    firstName: "Charles",
    lastName: "Leclerc",
    abbreviation: "LEC",
    number: 16,
    teamId: "ferrari",
    nationality: "Monegasque",
    countryCode: "MC",
    dateOfBirth: "1997-10-16",
    image: "/drivers/leclerc.png",
    slug: "charles-leclerc",
  },
  hamilton: {
    id: "hamilton",
    firstName: "Lewis",
    lastName: "Hamilton",
    abbreviation: "HAM",
    number: 44,
    teamId: "ferrari",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1985-01-07",
    image: "/drivers/hamilton.png",
    slug: "lewis-hamilton",
  },
  piastri: {
    id: "piastri",
    firstName: "Oscar",
    lastName: "Piastri",
    abbreviation: "PIA",
    number: 81,
    teamId: "mclaren",
    nationality: "Australian",
    countryCode: "AU",
    dateOfBirth: "2001-04-06",
    image: "/drivers/piastri.png",
    slug: "oscar-piastri",
  },
  russell: {
    id: "russell",
    firstName: "George",
    lastName: "Russell",
    abbreviation: "RUS",
    number: 63,
    teamId: "mercedes",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1998-02-15",
    image: "/drivers/russell.png",
    slug: "george-russell",
  },
  antonelli: {
    id: "antonelli",
    firstName: "Kimi",
    lastName: "Antonelli",
    abbreviation: "ANT",
    number: 12,
    teamId: "mercedes",
    nationality: "Italian",
    countryCode: "IT",
    dateOfBirth: "2006-08-25",
    image: "/drivers/antonelli.png",
    slug: "kimi-antonelli",
  },
  alonso: {
    id: "alonso",
    firstName: "Fernando",
    lastName: "Alonso",
    abbreviation: "ALO",
    number: 14,
    teamId: "aston_martin",
    nationality: "Spanish",
    countryCode: "ES",
    dateOfBirth: "1981-07-29",
    image: "/drivers/alonso.png",
    slug: "fernando-alonso",
  },
  stroll: {
    id: "stroll",
    firstName: "Lance",
    lastName: "Stroll",
    abbreviation: "STR",
    number: 18,
    teamId: "aston_martin",
    nationality: "Canadian",
    countryCode: "CA",
    dateOfBirth: "1998-10-29",
    image: "/drivers/stroll.png",
    slug: "lance-stroll",
  },
  gasly: {
    id: "gasly",
    firstName: "Pierre",
    lastName: "Gasly",
    abbreviation: "GAS",
    number: 10,
    teamId: "alpine",
    nationality: "French",
    countryCode: "FR",
    dateOfBirth: "1996-02-07",
    image: "/drivers/gasly.png",
    slug: "pierre-gasly",
  },
  colapinto: {
    id: "colapinto",
    firstName: "Franco",
    lastName: "Colapinto",
    abbreviation: "COL",
    number: 43,
    teamId: "alpine",
    nationality: "Argentine",
    countryCode: "AR",
    dateOfBirth: "2003-05-27",
    image: "/drivers/colapinto.png",
    slug: "franco-colapinto",
  },
  albon: {
    id: "albon",
    firstName: "Alex",
    lastName: "Albon",
    abbreviation: "ALB",
    number: 23,
    teamId: "williams",
    nationality: "Thai",
    countryCode: "TH",
    dateOfBirth: "1996-03-23",
    image: "/drivers/albon.png",
    slug: "alex-albon",
  },
  sainz: {
    id: "sainz",
    firstName: "Carlos",
    lastName: "Sainz",
    abbreviation: "SAI",
    number: 55,
    teamId: "williams",
    nationality: "Spanish",
    countryCode: "ES",
    dateOfBirth: "1994-09-01",
    image: "/drivers/sainz.png",
    slug: "carlos-sainz",
  },
  lawson: {
    id: "lawson",
    firstName: "Liam",
    lastName: "Lawson",
    abbreviation: "LAW",
    number: 30,
    teamId: "racing_bulls",
    nationality: "New Zealander",
    countryCode: "NZ",
    dateOfBirth: "2002-02-11",
    image: "/drivers/lawson.png",
    slug: "liam-lawson",
  },
  lindblad: {
    id: "lindblad",
    firstName: "Arvid",
    lastName: "Lindblad",
    abbreviation: "LIN",
    number: 27,
    teamId: "racing_bulls",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "2006-10-17",
    image: "/drivers/lindblad.png",
    slug: "arvid-lindblad",
  },
  ocon: {
    id: "ocon",
    firstName: "Esteban",
    lastName: "Ocon",
    abbreviation: "OCO",
    number: 31,
    teamId: "haas",
    nationality: "French",
    countryCode: "FR",
    dateOfBirth: "1996-09-17",
    image: "/drivers/ocon.png",
    slug: "esteban-ocon",
  },
  bearman: {
    id: "bearman",
    firstName: "Ollie",
    lastName: "Bearman",
    abbreviation: "BEA",
    number: 87,
    teamId: "haas",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "2005-05-08",
    image: "/drivers/bearman.png",
    slug: "ollie-bearman",
  },
  hulkenberg: {
    id: "hulkenberg",
    firstName: "Nico",
    lastName: "Hulkenberg",
    abbreviation: "HUL",
    number: 27,
    teamId: "audi",
    nationality: "German",
    countryCode: "DE",
    dateOfBirth: "1987-08-19",
    image: "/drivers/hulkenberg.png",
    slug: "nico-hulkenberg",
  },
  bortoleto: {
    id: "bortoleto",
    firstName: "Gabriel",
    lastName: "Bortoleto",
    abbreviation: "BOR",
    number: 5,
    teamId: "audi",
    nationality: "Brazilian",
    countryCode: "BR",
    dateOfBirth: "2004-10-14",
    image: "/drivers/bortoleto.png",
    slug: "gabriel-bortoleto",
  },
  hadjar: {
    id: "hadjar",
    firstName: "Isack",
    lastName: "Hadjar",
    abbreviation: "HAD",
    number: 6,
    teamId: "red_bull",
    nationality: "French",
    countryCode: "FR",
    dateOfBirth: "2004-09-28",
    image: "/drivers/hadjar.png",
    slug: "isack-hadjar",
  },
  bottas: {
    id: "bottas",
    firstName: "Valtteri",
    lastName: "Bottas",
    abbreviation: "BOT",
    number: 77,
    teamId: "cadillac",
    nationality: "Finnish",
    countryCode: "FI",
    dateOfBirth: "1989-08-28",
    image: "/drivers/bottas.png",
    slug: "valtteri-bottas",
  },
  perez: {
    id: "perez",
    firstName: "Sergio",
    lastName: "Perez",
    abbreviation: "PER",
    number: 11,
    teamId: "cadillac",
    nationality: "Mexican",
    countryCode: "MX",
    dateOfBirth: "1990-01-26",
    image: "/drivers/perez.png",
    slug: "sergio-perez",
  },
} as const;

export const DRIVER_LIST: Driver[] = Object.values(DRIVERS);

export function getDriverBySlug(slug: string): Driver | undefined {
  return DRIVER_LIST.find((driver) => driver.slug === slug);
}

export function getDriversByTeam(teamId: string): Driver[] {
  return DRIVER_LIST.filter((driver) => driver.teamId === teamId);
}
